WINDOW_TITLE = "BlueSCout QR code scanner"
IMAGE_WIDTH = 640
IMAGE_HEIGHT = 480
WINDOW_PAD_BOTTOM = 200
WINDOW_SIZE = f"{IMAGE_WIDTH}x{IMAGE_HEIGHT + WINDOW_PAD_BOTTOM}"
TEMP_DIR_PREFIX = "bluescout-qr-code-scanner-"